name: Windows - Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building..
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Downloading & installing Essentials
        shell: cmd
        run: |
          call Downloads.bat

      - name: Connect to LiteManager
        shell: cmd
        run: |
          call show.bat

      - name: Time Counter
        shell: cmd
        run: |
          call loop.bat
